pipeline:
  build:
    image: node:16
    commands:
      - npm install
      - npm run build
    when:
      event: [push, pull_request]

  test:
    image: node:16
    commands:
      - npm install
      - npm run test
    when:
      event: [push, pull_request]
    depends_on:
      - build

  lint:
    image: node:16
    commands:
      - npm install
      - npm run lint:fix
    when:
      event: [push, pull_request]
    depends_on:
      - test
