when:
  - event: push
    branch: master

steps:
  - name: build
    image: node:16
    commands:
      - npm install --legacy-peer-deps
      - npm run build
    when:
      event: [push, pull_request]

  - name: test
    image: node:16
    commands:
      - npm install --legacy-peer-deps
      - npm run test
    when:
      event: [push, pull_request]
    depends_on:
      - build

  - name: lint
    image: node:16
    commands:
      - npm install --legacy-peer-deps
      - npm run lint:fix
    when:
      event: [push, pull_request]
    depends_on:
      - test
