services:
  interactsh:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: interactsh:latest
    container_name: interactsh
    expose:
      - 80
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - './interactsh:/app/data'
networks:
  proxy:
    external: true
