services:
  interactsh-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: interactsh-web:latest
    container_name: interactsh-web
    expose:
      - 3000
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - './int-web-data:/data'
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/"]
      interval: 5s
      timeout: 20s
      retries: 10
networks:
  proxy:
    external: true
